### ISSUE TITLE
Why having two IF statements

### ISSUE THREAD

**Issue by janus** [jech/sbabeld#3]
`    if(i >= MAXNEIGHBOURS)
        expire_neighbours();
    if(i >= MAXNEIGHBOURS)
return -1;`

I was thinking that this would be okay.

`    if(i >= MAXNEIGHBOURS){
        expire_neighbours();
        return -1;
  }
`

**Comment by jech** [comment]
Thanks, fixed in 573127b1445f9d86779b06ada1ace37eb2720be3.
